web/router.ex
defmodule OnlineTv.Router do
  use OnlineTv.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug App.Restrict.AllowIframe
    plug OnlineTv.Auth, repo: OnlineTv.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", OnlineTv do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/schedule", PageController, :schedule
    get "/about", PageController, :about
    resources "/users", UserController, only: [:new, :create, :index, :show]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", OnlineTv do
    pipe_through [:browser, :authenticate_user]

    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", OnlineTv do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule OnlineTv.LayoutView do
  use OnlineTv.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>YNTBS</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

  <div class="container">
    <ul class="nav navbar-nav">
      <ul id="navigationbar">
        <ul id="logobg">
            <li class="YNTBS" id="Y">Y</li>
            <li class="YNTBS" id="N">N</li>
            <li class="YNTBS" id="T">T</li>
            <li class="YNTBS" id="char"></li>
            <ul id="bs">
              <li id="B">Broadcasting</li>
              <li id="S">System </li>          
            </ul>
        </ul>
      </ul>
        <ul id="logininfo">
          <%= if @current_user do %>
            <span><%= link "videos", to: video_path(@conn, :index)%></span>
            <span><%= link "Log out", to: session_path(@conn, :delete, @current_user), method: "delete" %></span>
            <span><%= @current_user.username %></span>        
          <% end %>
        </ul>
    </ul>
    <ul id="links">
      <!-- <span class="navigation"><%= link "Watch", to: page_path(@conn, :index) %></span> -->
      <span><i>Watch cool videos together with the internet</i></span>
    </ul>
  </div>



    <div id="containerfluid" class="container-fluid">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->

    <footer class="footer">
      <div class='container'>
        <!---<span ><%= link "About", to: page_path(@conn, :about) %></span> -->
        <div id="nicolaasdanneels">Made by <a href="mailto:yntbscontact@gmail.com">Nicolaas Danneels</a></div>
        <div id="nicolaasdanneels">Powered by the YouTube API and Twitter API</div>
      </div>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>